public with sharing class ChatterConstant {
    /*
    public static String LINK                   = 'Link';
	public static String ENTITY_LINK            = 'EntityLink';
	public static String TEXT                   = 'Text';
	public static String MENTION                = 'Mention';
	public static String P_TAG                  = 'p';
	public static String DIV_TAG                = 'div';
	public static String BOLD_TAG               = 'strong';
	public static String ITALIC_TAG             = 'em';
	public static String UNDERLINE_TAG          = 'u';
	public static String ORDERLIST_TAG          = 'ol';
	public static String UNORDERLIST_TAG        = 'ul';
	public static String SPAN_TAG               = 'span';
	public static String LISTELEMENT_TAG        = 'li';
	public static String LINK_TAG               = 'a';
	public static String STRIKE_TAG             = 's';
	public static String CODE                       = 'code';
	public static String TOK_CLASSIC            = 'TOK_CLASSIC';
	public static String TOK_DARK               = 'TOK_DARK';
	public static String LATEST_POSTS           = 'Latest Posts';
	public static String MOST_RECENT_ACTIVITY   = 'Most Recent Activity';

	public static String FILE                   = 'FILE';
	public static String CHATTERGROUP           = 'CHATTERGROUP';
	public static String RECOMENDEDOBJECT       = 'RECOMENDEDOBJECT';
	public static String UNAUTHENTICATEUSER     = 'UNAUTHENTICATEUSER';

	public static String USER                   = 'USER';
	public static String OTHER                  = 'OTHER';

	public static String CONTENT                = 'CONTENT';
	public static String ORIGIN                 = 'ORIGIN';

	public static String MESSAGE_EVENT          = 'e.oktana_desktop:chatterNotificationMessageEvent';
	public static String PROFILE_EVENT          = 'e.oktana_desktop:chatterNotificationProfileEvent';
	public static String COMMUNITY_EVENT        = 'e.oktana_desktop:chatterNotificationCommunityEvent';
	public static String OBJECT_EVENT       = 'e.oktana_desktop:chatterNotificationObjectEvent';
	public static String GROUP_EVENT            = 'e.oktana_desktop:chatterNotificationGroupEvent';
	public static String STATUS_EVENT           = 'e.oktana_desktop:chatterCurrentStatusChangeEvent';

	public static String ROOT_MANAGE_KEY        = 'bv5Q2IX2OKkmjL9BiPFgrji6fxiA7ckD0O4juFqfTzk=';

	public static String APPID = '3ec4e8c1-0271-4233-a6ca-9f85d5d191e7';
	public static String APIKEY = 'MzJkOTA0NWYtYzlhOS00NWYwLTg4NDEtYzk1YzI5Njg0NGRh';
  
	public static String PLAYERSENDPOINT = 'https://onesignal.com/api/v1/players';
	public static String NOTIFICATIONENPOINT = 'https://onesignal.com/api/v1/notifications';
    */

	//Developer credentials

	//public static String FIREBASEENDPOINT = 'https://tok-testing.firebaseio.com/';
	//public static String FIREBASESECRET = 'qxBMimMisG5yqa5Idnx1KV0Csqm7BwZoVYTeKTFB';

	//Production credentials

	//public static String FIREBASEENDPOINT = 'https://tok-mobile.firebaseio.com/';
	//public static String FIREBASESECRET = '7r06l7TDqkgBGOcFtF4qPJsXydhNSs5NdCu2SHUT';
	
	//public static final Integer SUCCESS_POST_CODE = 201;
	//public static final Integer SUCCESS_GET_CODE = 200;
	//public static String SERVICE_ENDPOINT     = 'https://chatter-desktop.servicebus.windows.net:443/';
	//public static String NOTIFICATION_ENDPOINT    = 'https://chatter-desktop.servicebus.windows.net:443/chatter-desktop/messages';

	//public static ConnectApi.MarkupType Bold            = ConnectApi.MarkupType.Bold;
	//public static ConnectApi.MarkupType Italic          = ConnectApi.MarkupType.Italic;
	//public static ConnectApi.MarkupType ListItem        = ConnectApi.MarkupType.ListItem;
	//public static ConnectApi.MarkupType OrderedList     = ConnectApi.MarkupType.OrderedList;
	//public static ConnectApi.MarkupType Paragraph       = ConnectApi.MarkupType.Paragraph;
	//public static ConnectApi.MarkupType StrikeThrough   = ConnectApi.MarkupType.StrikeThrough;
	//public static ConnectApi.MarkupType Underline       = ConnectApi.MarkupType.Underline;
	//public static ConnectApi.MarkupType UnorderedList   = ConnectApi.MarkupType.UnorderedList;

	// A feed item has a single parent and is scoped to one community or across all communities. 
	// A feed item can have capabilities such as bookmarks, canvas, content, comment, link, poll. 
	// Feed items have a body made up of message segments that can always be gracefully degraded to text-only values.
	//public static ConnectApi.FeedElementType FeedItem   = ConnectApi.FeedElementType.FeedItem;
	// A container of feed elements. A bundle also has a body made up of message segments that can always be gracefully degraded to text-only values.
	//public static ConnectApi.FeedElementType Bundle     = ConnectApi.FeedElementType.Bundle;
	// A recommendation is a feed element with a recommendations capability. 
	// A recommendation suggests records to follow, groups to join, or applications that are helpful to the context user.
	//public static ConnectApi.FeedElementType Recommendation     = ConnectApi.FeedElementType.Recommendation;
	//public static Integer SALESFORCE_USERNAME_LIMIT = 80;
	//public static Integer SALESFORCE_REMOTE_SITE_NAME_LIMIT = 40;

	//this is the url for the service to get the cross org users
	//development
	//public static String URL_GET_USERS_CROSS_ORG = '/services/apexrest/TokCrossOrgUsers';
	//production/package
	//public static String URL_GET_USERS_CROSS_ORG = '/services/apexrest/oktana_desktop/TokCrossOrgUsers';

	//apex classes to add to the site's profile
	//development
	//public static String CROSS_ORG_USERS_APEX_CLASS = 'CrossOrgUsers';
	//production/package
	//public static String CROSS_ORG_USERS_APEX_CLASS = 'oktana_desktop__CrossOrgUsers';
	//Slack endpoints

	//public static String SLACK_AUTHORIZE_ENDPOINT = 'https://slack.com/api/oauth.v2.access?';
	//public static String SLACK_UNINSTALL_ENDPOINT = 'https://slack.com/api/apps.uninstall?';
	//public static String SLACK_FIREBASE = '/slack/jobResult';
	//public static String SLACK_ROOT_FIREBASE = 'slack/';
	//public static String SLACK_WORKSPACES = '/slack/workspaces/';
	//public static String SLACK_KEY = '/slack/savedKey';
	//public static String SLACK_KEY_LONG = '/slack/savedKey/key';
	//public static String SLACK_REDIRECT_URI = 'https%3A%2F%2Fus-central1-tok-mobile.cloudfunctions.net%2FreceiveSlackCode%3F';
	//public static String TokConversationRecordTypeDevName = 'Tok_Conversation';
	public static String SlackConversationRecordTypeDevName = 'Slack';
	//public static String SlackUserName = 'Integration';
	public static Integer SLACK_MESSAGES_LIMIT = 100;
	//public static Integer SLACK_CONVERSATIONS_LIMIT = 40;
	public static String cryptoKey = 'CuVDQFRtlbP9TbpJMXDdXQ==';


	public static Integer MAX_FIELD_LENGTH = 131072;
	public static Integer MAX_CHARS_UNTIL_TS_FIELD_RESET = 95058;
}
