public class Constants {
    //Contants for HTTP Integrations
    public static final String CALLOUT_HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String CALLOUT_HEADER_ACCEPT = 'Accept';
    public static final String CALLOUT_HEADER_CONTENT_TYPE_APPLICATION_JSON = 'application/json';
    public static final String CALLOUT_HEADER_CONTENT_TYPE_APPLICATION_URLENCODED = 'application/x-www-form-urlencoded';
    public static final String CALLOUT_HEADER_AUTH = 'Authorization';
    public static final String CALLOUT_HEADER_BEARER_AUTH = 'Bearer ';
    public static final String HTTP_GET = 'GET';
    public static final String HTTP_POST = 'POST';
    public static final String SLACK_ENDPOINT = 'https://slack.com/api/';
    public static final Integer SPLIT_LIMIT = 98;
}
